# GlobalSettings.yml

---
conf.py:
  today_fmt: '%Y-%m-%d %H:%M'

  extensions:
  - sphinx.ext.extlinks
  - sphinx.ext.ifconfig
  - sphinx.ext.intersphinx
  - sphinx.ext.todo
  - t3sphinx.ext.targets

  extlinks:
    forge:
    - https://forge.typo3.org/issues/%s
    - 'forge: '

  intersphinx_mapping:

    t3admin:
    - http://preview.docs.typo3.org/TYPO3/AdministratorsGuide
    - null

    t3api:
    - http://preview.docs.typo3.org/TYPO3/CoreApiReference
    - null

    t3cgl:
    - http://preview.docs.typo3.org/TYPO3/CodingGuidelinesReference
    - null

    t3editors:
    - http://preview.docs.typo3.org/TYPO3/EditorsTutorial
    - null

    #t3extbasebook:
    #-
    #- null

    t3fal:
    - http://preview.docs.typo3.org/TYPO3/FileAbstractionLayerReference
    - null

    t3start:
    - http://preview.docs.typo3.org/TYPO3/GettingStartedTutorial
    - null

    t3inside:
    - http://preview.docs.typo3.org/TYPO3/InsideTypo3Reference
    - null

    t3install:
    - http://preview.docs.typo3.org/TYPO3/InstallationGuide
    - null

    # t3isr:
    # - http://preview.docs.typo3.org/TYPO3/IndexedSearchReference
    # - null

    t3l10n:
    - http://preview.docs.typo3.org/TYPO3/FrontendLocalizationGuide
    - null

    t3security:
    - http://preview.docs.typo3.org/TYPO3/SecurityGuide
    - null

    t3services:
    - http://preview.docs.typo3.org/TYPO3/Typo3ServicesReference
    - null

    t3skinning:
    - http://preview.docs.typo3.org/TYPO3/SkinningReference/
    - null

    t3tca:
    - http://preview.docs.typo3.org/TYPO3/TCA-Reference
    - null

    # t3templating:
    #-
    #- null

    t3ts45:
    - http://preview.docs.typo3.org/TYPO3/TyposcriptIn45MinutesTutorial
    - null

    t3tsconfig:
    - http://preview.docs.typo3.org/TYPO3/TSconfigReference
    - null

    t3tsref:
    - http://preview.docs.typo3.org/TYPO3/TyposcriptReference
    - null

    t3tssyntax:
    - http://preview.docs.typo3.org/TYPO3/TyposcriptSyntaxReference
    - null

  highlight_language: 'php'

...
